name: Push docker to ghcr.io

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Login to registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build image and push it'
        run: |
          docker build . --tag ghcr.io/n0d4n/musicbot:latest
          docker push ghcr.io/n0d4n/musicbot:latest